# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\core_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(840, 437)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.device = QtWidgets.QComboBox(self.centralwidget)
        self.device.setGeometry(QtCore.QRect(10, 10, 231, 22))
        self.device.setEditable(False)
        self.device.setObjectName("device")
        self.rb_rx = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_rx.setGeometry(QtCore.QRect(440, 10, 21, 21))
        self.rb_rx.setStyleSheet("")
        self.rb_rx.setText("")
        self.rb_rx.setIconSize(QtCore.QSize(32, 32))
        self.rb_rx.setCheckable(True)
        self.rb_rx.setChecked(False)
        self.rb_rx.setAutoRepeat(False)
        self.rb_rx.setObjectName("rb_rx")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(410, 10, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.rb_tx = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_tx.setGeometry(QtCore.QRect(370, 10, 21, 21))
        self.rb_tx.setStyleSheet("")
        self.rb_tx.setText("")
        self.rb_tx.setIconSize(QtCore.QSize(32, 32))
        self.rb_tx.setCheckable(True)
        self.rb_tx.setAutoRepeat(False)
        self.rb_tx.setObjectName("rb_tx")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 10, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.erx = QtWidgets.QPushButton(self.centralwidget)
        self.erx.setGeometry(QtCore.QRect(320, 50, 75, 23))
        self.erx.setObjectName("erx")
        self.etx = QtWidgets.QPushButton(self.centralwidget)
        self.etx.setGeometry(QtCore.QRect(400, 50, 75, 23))
        self.etx.setObjectName("etx")
        self.forward_button = QtWidgets.QPushButton(self.centralwidget)
        self.forward_button.setGeometry(QtCore.QRect(10, 40, 111, 31))
        self.forward_button.setObjectName("forward_button")
        self.reverse_button = QtWidgets.QPushButton(self.centralwidget)
        self.reverse_button.setGeometry(QtCore.QRect(130, 40, 111, 31))
        self.reverse_button.setObjectName("reverse_button")
        self.rb_conn = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_conn.setGeometry(QtCore.QRect(300, 10, 21, 21))
        self.rb_conn.setStyleSheet("")
        self.rb_conn.setText("")
        self.rb_conn.setIconSize(QtCore.QSize(32, 32))
        self.rb_conn.setCheckable(True)
        self.rb_conn.setChecked(False)
        self.rb_conn.setAutoRepeat(False)
        self.rb_conn.setObjectName("rb_conn")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 10, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.connection_test = QtWidgets.QPushButton(self.centralwidget)
        self.connection_test.setGeometry(QtCore.QRect(10, 80, 111, 31))
        self.connection_test.setObjectName("connection_test")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DTU v0.1"))
        self.device.setToolTip(_translate("MainWindow", "<html><head/><body><p>Выберите устройство</p><p><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "RX"))
        self.label_2.setText(_translate("MainWindow", "TX"))
        self.erx.setText(_translate("MainWindow", "EMMIT RX"))
        self.etx.setText(_translate("MainWindow", "EMMIT TX"))
        self.forward_button.setText(_translate("MainWindow", "FORWARD"))
        self.reverse_button.setText(_translate("MainWindow", "REVERSE"))
        self.label_3.setText(_translate("MainWindow", "CONN"))
        self.connection_test.setText(_translate("MainWindow", "CONNECTION TEST"))
